name: Build and push pages

on: push

jobs:
  build:
    name: Build and push pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run build script
        run: node scripts/build.js
