name: pages sync and build

on: push

jobs:
  sync:
    name: sync and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Squash sync
        run: |
          git fetch origin
          git merge --squash origin/main
          git restore --staged *
          git add *
          git commit
      - name: Build pages
        run: |
          npm ci
          npm start
        working-directory: ./src/packages/build
      - name: Commit pages
        run: |
          git add *
          git commit -m "Build pages"
      - name: Push
        run: git push
