name: pages build and push

on: push

jobs:
  sync:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: out
      - name: Setup git identity
        run: |
          git config --global user.email "69427105+jonasmusall@users.noreply.github.com"
          git config --global user.name "jonasmusall"
      - name: Empty output directory
        run: git rm -rf .
        working-directory: ./out
      - name: Build pages
        run: |
          npm ci
          npm start
        working-directory: ./packages/build
      - name: Commit and push build
        run: |
          git add .
          git commit -m "Build pages"
          git push
        working-directory: ./out
